### ISSUE TITLE
 USER STORY: Recipes Content from Online External Sources

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#12]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Content Management |
| Epic | Recipes Content |
| User Story | As a content manager, I want to source recipes from online resources and store references for credit so that we can offer a wide range of options while respecting intellectual property. |
| Story Points | 2 |

## Description
As a content manager, I want to source recipes from online resources and store references for crediting, so that we can offer a wide range of options while respecting intellectual property.

## Acceptance Criteria
1. Make sure the recipes align with our theme
2. Make sure we are not violating intellectual property 
3. Make sure the data and metadata align with our JSON structure

## Tasks
- [x] Search for recipes and save the URL and necessary data
- [x] Keep the information accessible for development and implementation
- [x] Communicate with the person in charge if you forgot the data needed from those recipes
- [x] Make sure we are not violating any intellectual property

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
