### ISSUE TITLE
 USER STORY: Recipes Content and their Data Structure with JSON

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#14]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Content Management |
| Epic | Recipes Content |
| User Story | As a content coordinator, I want to define the data structure for recipes so that they are consistent, easy to manage, and user-friendly. |
| Story Points | 2 |

## Description
As a content coordinator, I want to define the data structure for recipes, so that they are consistent, easy to manage, and user-friendly.

## Acceptance Criteria
1. Make sure the data structure is aligned with the proposed display of information
2. Make sure the data is properly tagged with an ID for easy manipulation
3. Make sure the members of the team know what data they are looking for and manipulating

## Tasks
- [x] Use proper syntax and key-value pairs defining our data structure
- [x] Add an ID to each entry for easy manipulation
- [x] Send a message to the team to warn them about the updates or the final data structure so that they don't make mistakes in the coming iterations

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
