### ISSUE TITLE
 USER STORY: Navbar Integration, Style & Considerations

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#15]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Navigation |
| Epic | Navbar |
| User Story | As a UX designer, I want to add and/or manipulate a navbar compatible with our overall design, so that users can navigate our site easily and intuitively.|
| Story Points | 2 |

## Description
As a UX designer, I want to add and/or manipulate a navbar compatible with our overall design, so that users can navigate our site easily and intuitively.

## Acceptance Criteria
1. Make sure the navbar aligns with our overall design
2. Make sure the navbar is actually functional
3. Make sure the navbar is responsive and has at least placeholders for useful links

## Tasks
- [x] Recheck the template for some integrated navbar DRY! Do not reinvent the wheel!
- [x] Test the navbar on mobile phones as well, it usually fails in mobile versions
- [x] Make sure it will not disturb the overall user experience and that it is responsive and inclusive
- [x] Pay attention to accessibility, ARIA labels where needed

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
