### ISSUE TITLE
 USER STORY: Navbar & Entries Definition

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#16]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Navigation |
| Epic | Navbar |
| User Story | As a web developer, I want to define navbar entries clearly so that users can find the most important sections of our site quickly. |
| Story Points | 1 |

## Description
As a web developer, I want to define navbar entries clearly, so that users can find the most important sections of our site quickly.

## Acceptance Criteria
1. Make sure you check for agreed content strategies
2. Make sure you are pointing to the correct sections or pages
3. Make sure the overall style aligns with our project design

## Tasks
- [x] Make sure you start checking the outlines, mockups and, documentation for agreed content strategies
- [x] Implement same-page linking where needed as well as to other local pages
- [x] Watch out for fonts and font sizes following the convention we agreed upon

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
