### ISSUE TITLE
 USER STORY: Color Scheme & Alignment with Christmas's spirit

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#17]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Visual Design |
| Epic | Color Scheme |
| User Story | As a graphic designer, I want to select a color palette incorporating key Christmas colors so that the website resonates with the festive theme. |
| Story Points | 2 |

## Description
As a graphic designer, I want to select a color palette incorporating key Christmas colors, so that the website resonates with the festive theme.

## Acceptance Criteria
1. Make sure the chosen colors are truly what we decided
2. Make sure we use proper psychology of colors and smart decisions
3. Make sure all team members know about the last color decisions

## Tasks
- [x] Check the documentation or planning to make sure we chose the right colors
- [x] Rethink the psychology of colors and how they can benefit our final product
- [x] Update proper root variables on the project to acquire the pallet and inform the rest of the team to align with it

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
