### ISSUE TITLE
 USER STORY: Color Scheme Implementation

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#18]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Visual Design |
| Epic | Color Scheme |
| User Story | As a designer, I want to apply the color scheme consistently across the website's elements so that it enhances the visual appeal and user experience. |
| Story Points | 2 |

## Description
As a designer, I want to apply the color scheme consistently across the website's elements, so that it enhances the visual appeal and user experience.

## Acceptance Criteria
1. Make sure the project has evolved considerably to start with this user story
2. Make sure the colors are correct and align with our plan
3. Make sure you communicate with your teammates for normal and important changes

## Tasks
- [x] Verify the project has grown enough to start applying the color scheme ONLY to those features and functionalities already finished
- [x] Confirm and follow the agreed scheme plan
- [x] Communicate effectively with your teammates they may forget to mark their tasks as completed or DONE

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
