### ISSUE TITLE
 USER STORY: Calendar Section with Models as an Alternative for User Experience 

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#19]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Interaction |
| Epic | Calendar Section |
| User Story | As a developer, I want to implement an alternative model functionality for calendar users so that they have a choice in how they view content. |
| Story Points | 7 |

## Description
As a developer, I want to implement an alternative model functionality for calendar users so that they have a choice in how they view content.

## Acceptance Criteria
1. Make sure the team agrees on creating a calendar of this type
2. Make sure the calendar uses the same database
3. Make sure the calendar is user-friendly and responsive, exploit Bootstrap resources

## Tasks
- [x] Develop a calendar that is clickable and opens a model section with the recipe, it should look like a surprise
- [x] Connect the calendar with the database in a way that it will fetch random recipes each time it is clicked
- [x] Use Bootstrap cards or your implementation, follow the mockup and guidelines to align with the project's overall design, structure, and style
- [x] Implement if agreed upon the favorite functionality to store data on the user's session
- [x] Imitate the slider's progressive disclosure, structure, and overall design for consistency

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
