### ISSUE TITLE
 USER STORY: Calendar Section, Comparison and Research

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#20]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Interaction |
| Epic | Calendar Section |
| User Story | As a UX researcher, I want to research and compare user engagement: slider vs calendar, so that we can understand which is more effective for our audience, maybe both. |
| Story Points | 2 |

## Description
As a UX researcher, I want to research and compare user engagement: slider vs calendar, so that we can understand which is more effective for our audience, maybe both.

## Acceptance Criteria
1. Make sure the team still agrees on the possibility of creating a calendar @plexoio is willing to work on it
2. Make sure the research is based on quality sources, it doesn't have to be that deep
3. Make sure we agree that both implementation Slider and Calendar are the proper approach

## Tasks
- [x] Invite @plexoio to develop a proper calendar following the other user story for that matter
- [x] Share on this user story the research about the usage of both calendar and slider for extra learning
- [x] Communicate effectively with the team and follow the design guidelines to implement and adapt the calendar

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
The agreement is that both functionalities are necessary for the separation of concerns. Since a slider is usually eye-catching and engaging it should be the main user interaction. Therefore, adding a calendar will direct the user to the "main" initial concept of the project. In conclusion, the synergy is undoubtedly present, and without any of them, the project will not be the same.
