### ISSUE TITLE
 USER STORY: Hero Section, Content and SEO

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#23]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | CTA Design |
| Epic | Hero Section|
| User Story | As a content strategist, I want to design an engaging intro section with relevant content and keywords so that it appeals to our target audience and improves SEO. |
| Story Points | 4 |

## Description
As a content strategist, I want to design an engaging intro section with relevant content and keywords, so that it appeals to our target audience and improves SEO.

## Acceptance Criteria
1. Make sure the content display aligns with our thematic
2. Make sure you are following the guidelines and overall user experience and design
3. Make sure you communicate with other teammates for help if necessary
4. Make sure it is responsive

## Tasks
- [x] Search and implement proper keywords and phrasing
- [x] Edit the CTA button, if existing, in an attractive manner that aligns with SEO and accessibility
- [x] Invite other team members to try, experience and give feedback on the implementation
- [x] Add other tasks if necessary

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
