### ISSUE TITLE
 USER STORY: Hero Section, CTA Button

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#24]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | CTA Design |
| Epic | Hero Section |
| User Story | As a web developer, I want to develop a clear and prominent call-to-action button so that it guides users to take desired actions. |
| Story Points | 2 |

## Description
As a web developer, I want to develop a clear and prominent call-to-action button, so that it guides users to take desired actions.

## Acceptance Criteria
1. Make sure the button aligns with the overall design
2. Make sure you are following the guidelines or mockups
3. Make sure you are considering mobile screen first and interaction

## Tasks
- [x] Develop a button that will connect the users to the next most important part of the website, the Slider?
- [x] Implement a design, color and, font according to the overall plan for consistency
- [x] Make sure you are testing properly the visuals and functionality
- [x] Add more tasks if necessary

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
