### ISSUE TITLE
 USER STORY: Accountability and FAQ Section

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#29]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Support |
| Epic | Accountability |
| User Story | As a customer service manager, I want to develop a comprehensive and user-friendly FAQ section so that users can easily find answers to their questions. |
| Story Points | 4 |

## Description
As a customer service manager, I want to develop a comprehensive and user-friendly FAQ section, so that users can easily find answers to their questions.

## Acceptance Criteria
1. Make sure the FAQ questions are indeed useful
2. Make sure the overall design aligns with the mockups and what we have agreed upon
3. Make sure the questions are interactive enough and that they use progressive disclosure

## Tasks
- [x] Create another section or page to host the structure of the FAQ
- [x] Exploit Bootstrap to implement the FAQ respecting the overall design of the project
- [ ] Contact other teammates for the keywords and phrasing to use or just opinions from them
- [x] Add interactivity with CSS and JS to the section
- [x] Use JSON to store FAQ content
- [ ] Make sure it aligns with the overall design
- [ ] Solve the slow-down dropdown (issue on the live project only)

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
I have used the JSON API to work much better the content so that we don't overload the index.html or homepage.

1. I have reused some code I had, improved it, and adapted it for our project.
2. I have used GPT-4 to speed up the function commenting and improve the understanding of the code.
3. The section is responsive.
4. The interactivity is intuitive enough.
5. I added real data instead of dummy data

![FAQ1](https://github.com/Erikas-Ramanauskas/Christmas-hackathon/assets/127787526/55a5371d-3343-4648-afd9-62a2f7142329)

![faq2](https://github.com/Erikas-Ramanauskas/Christmas-hackathon/assets/127787526/dc57acf9-c659-4cb5-b73b-ee199d8811f4)
