### ISSUE TITLE
 USER STORY: Accountability and Contact Form with EmailJS

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#30]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Support |
| Epic # | Accountability |
| User Story # | As a web developer, I want to create a functional contact form using EmailJS so that users can contact us efficiently and we can manage inquiries effectively. |
| Story Points | 4 |

## Description
As a web developer, I want to create a functional contact form using EmailJS so that users can contact us efficiently and we can manage inquiries effectively.

## Acceptance Criteria
1. Make sure you DRY the process and reuse what your teammates have already built
2. Make sure the contact form is user-friendly, interactive, intuitive & responsive
4. Make sure the contact form does not fail over due to connections with Google if set that way

## Tasks
- [x] Exploit Bootstrap to create an interactive and responsive contact form
- [x] Remember to apply defensive programming, and success/error messages to the user
- [x] Recheck configuration from EmailJS side not to sleep or disconnect from Google if set up that way
- [ ] Adapt implementation with the overall design

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
I am not reusing @eandablo recipe form, instead, I adapted a contact form from another project I had, I refactored a lot and now it aligns better with our project.

**Comment by plexosoft** [comment]
1. The alert appears after a successful message or error and JS will focus the user on the notification
2. The implementation works just fine after testing with @MiaRasmussen05 from her end
3. Static defensive programming implemented: disable Send button after successful/error attempt

![as success](https://github.com/Erikas-Ramanauskas/Christmas-hackathon/assets/127787526/d7830f06-34fb-4615-9e5b-e892e782c39c)
![as error](https://github.com/Erikas-Ramanauskas/Christmas-hackathon/assets/127787526/210704a0-a210-49d0-a085-226b5f598e9d)
