### ISSUE TITLE
 USER STORY: Accountability and About Section

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#31]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Support |
| Epic | Accountability |
| User Story | As a marketing manager, I want to build an informative and SEO-optimized About section so that it improves our site's visibility and provides valuable information. |
| Story Points |  2 |

## Description
As a marketing manager, I want to build an informative and SEO-optimized About section so that it improves our site's visibility and provides valuable information.

## Acceptance Criteria
1. Make sure the About section holds crucial data about the project
2. Make sure the About section follows SEO standards
3. Make sure the About section aligns with the overall structure and design

## Tasks
- [ ] Create another section or page exploiting Bootstrap resources
- [ ] Make sure the fonts, structure and color truly aligns with the project
- [ ] Collaborate if needed with other teammates for the SEO, wording and phrasing

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Idea disregarded!
