### ISSUE TITLE
 USER STORY: Team Section, Implementation, Guidelines and Reminders

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#32]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Team Pride |
| Epic | Team Section |
| User Story | As a content strategist, I want to build a friendly and interactive team section so that it improves our site's authority and promotes trust. |
| Story Points | 4  |

## Description
As a content strategist, I want to build a friendly and interactive team section so that it improves our site's authority and promotes trust.

## Acceptance Criteria
1. Make sure the team section is inclusive and provides relevant data without compromising the privacy of the developers
2. Make sure the overall style truly aligns with the desired outcome
3. Make sure it is responsive and does function well across different browsers and devices

## Tasks
- [x] Use an online resource to adapt and improve the team section, save the link for the documentation
- [x] Implement the feature exploiting Bootstrap to speed up the development process
- [x] Make use of different technologies such as CSS, HTML, and JS to add a proper code structure or extra style, and interaction
- [x] Consider accessibility with ARIA Labels
- [x] Add more tasks here for reminders if necessary

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
