### ISSUE TITLE
 USER STORY: Dynamic Recipe Sharing Functionality With Google

### ISSUE THREAD

**Issue by plexosoft** [Erikas-Ramanauskas/Christmas-hackathon#35]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Interaction |
| Epic | Recipe Sharing |
| User Story | As a developer, I want to build on top of the current recipe features a user-sharing capability so that it improves our site's user experience and engagement. |
| Story Points | 7 |

## Description
As a developer, I want to build on top of the current recipe features a user-sharing capability so that it improves our site's user experience and engagement.

## Acceptance Criteria
1. Make sure the user understands they can share recipes of their own
2. Make sure the functionality aligns properly with the overall project plan
3. Make sure the sharing functionality is stable on Google's side and the user's side

## Tasks
- [ ] Develop a feature that will allow users to share recipes on our static website using Google Sheets as a database
- [ ] Implement the new functionality in a semi-full stack manner, respecting progressive disclosure and 3 clicks-max rule
- [ ] Align the feature so that it looks and interacts great with the overall design
- [ ] Make sure it is working on different screen sizes and browsers
- [ ] Remember to implement ARIA labels for accessibility where necessary
- [ ] Be in touch with the team for feedback and improvements

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexosoft** [comment]
Hey Efren! If you still need help with this one don't hesitate to invite any of us!

**Comment by plexosoft** [comment]
Idea disregarded!
