### ISSUE TITLE
 USER STORY: Snowfall effect

### ISSUE THREAD

**Issue by Erikas-Ramanauskas** [Erikas-Ramanauskas/Christmas-hackathon#41]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Style |
| Epic # | Fallign snow |
| User Story # | Fallign snow  |
| Story Points | 2 |

## Description
**As a** User I want to see the fall effect across the entire website,

**I want** Falling Snow,

**So that** Snow Fall

## Acceptance Criteria
1. Now the effect falls from the top of the screen to the bottom
2. The speed of the fall is random
3. The direction of snowflake fall is random

## Tasks
- [x] Create a snowflake image.
- [x] Snoflakes must fall in random order
- [x] Snoflakes must fall at random speed
- [x] Snoflakes must fall in a random direction
- [x] Snoflakes must disappear at the bottom of screen

## Notes
* Articulate this criterion collaboratively with the Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Scrum Master.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
